apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: jdavis-se-jboss
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d6886839276f209cbead40d2035c69bfdcc3f53502ea6e1b70bfd98e39546802
        name: container-image
        resources: {}
status: {}
